/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{ts,tsx}',
    './src/components/**/*.{ts,tsx}',
    './src/widgets/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: 'var(--color-primary-50)',
          100: 'var(--color-primary-100)',
          200: 'var(--color-primary-200)',
          300: 'var(--color-primary-300)',
          400: 'var(--color-primary-400)',
          500: 'var(--color-primary-500)',
          600: 'var(--color-primary-600)',
          700: 'var(--color-primary-700)',
          800: 'var(--color-primary-800)',
          900: 'var(--color-primary-900)',
        },
        secondary: {
          50: 'var(--color-secondary-50)',
          100: 'var(--color-secondary-100)',
          200: 'var(--color-secondary-200)',
          300: 'var(--color-secondary-300)',
          400: 'var(--color-secondary-400)',
          500: 'var(--color-secondary-500)',
          600: 'var(--color-secondary-600)',
          700: 'var(--color-secondary-700)',
          800: 'var(--color-secondary-800)',
          900: 'var(--color-secondary-900)',
        },
        accent: {
          50: 'var(--color-accent-50)',
          100: 'var(--color-accent-100)',
          200: 'var(--color-accent-200)',
          300: 'var(--color-accent-300)',
          400: 'var(--color-accent-400)',
          500: 'var(--color-accent-500)',
          600: 'var(--color-accent-600)',
          700: 'var(--color-accent-700)',
          800: 'var(--color-accent-800)',
          900: 'var(--color-accent-900)',
        },
        neutral: {
          50: 'var(--color-neutral-50)',
          100: 'var(--color-neutral-100)',
          200: 'var(--color-neutral-200)',
          300: 'var(--color-neutral-300)',
          400: 'var(--color-neutral-400)',
          500: 'var(--color-neutral-500)',
          600: 'var(--color-neutral-600)',
          700: 'var(--color-neutral-700)',
          800: 'var(--color-neutral-800)',
          900: 'var(--color-neutral-900)',
        },
      },
      spacing: {
        news: {
          xs: 'var(--spacing-xs)',
          sm: 'var(--spacing-sm)',
          md: 'var(--spacing-md)',
          lg: 'var(--spacing-lg)',
          xl: 'var(--spacing-xl)',
          '2xl': 'var(--spacing-2xl)',
        },
      },
      borderRadius: {
        news: {
          sm: 'var(--radius-sm)',
          md: 'var(--radius-md)',
          lg: 'var(--radius-lg)',
          xl: 'var(--radius-xl)',
        },
      },
      fontSize: {
        'news-xs': ['var(--font-size-xs)', { lineHeight: 'var(--line-height-xs)' }],
        'news-sm': ['var(--font-size-sm)', { lineHeight: 'var(--line-height-sm)' }],
        'news-base': ['var(--font-size-base)', { lineHeight: 'var(--line-height-base)' }],
        'news-lg': ['var(--font-size-lg)', { lineHeight: 'var(--line-height-lg)' }],
        'news-xl': ['var(--font-size-xl)', { lineHeight: 'var(--line-height-xl)' }],
        'news-2xl': ['var(--font-size-2xl)', { lineHeight: 'var(--line-height-2xl)' }],
        'news-3xl': ['var(--font-size-3xl)', { lineHeight: 'var(--line-height-3xl)' }],
      },
      boxShadow: {
        'news-sm': 'var(--shadow-sm)',
        'news-md': 'var(--shadow-md)',
        'news-lg': 'var(--shadow-lg)',
        'news-xl': 'var(--shadow-xl)',
      },
    },
  },
  plugins: [],
};
